### ISSUE TITLE
Consider shortening namespace URL and moving to /

### ISSUE THREAD

**Issue by ldodds** [openactive/modelling-opportunity-data#120]
Should we update namespace for 2.0 to use: `https://openactive.io/ns#` or perhaps `https://openactive.io/ns/`

Slightly short url. I don't want to lose the https as [others are migrating that way](https://schema.org/docs/faq.html#19) (slowly).

Main issue with a switch to "/" based URL is that we don't have any easy way to serve a context that works for 1.0 and 2.0 so there's small chance that it might break something for older users.

**Comment by nickevansuk** [comment]
Agree with `https`, if that's where schema.org is going then makes sense for us to start there for the sake of one character and making the internet safer.

`/` would be consistent with schema.org, and lends itself to good documentation (we could link to our [docs](https://developer.openactive.io/) this way? We could redirect openactive.io/ns* to developer.openactive.io/ns/* pretty easily, or just host the developer docs at the root to match schema - though the latter could create search confusion.

`#` makes it easy to split on '#' when processing the data.

Are there any other pros and cons?

**Comment by nickevansuk** [comment]
Perhaps given the recent advent of https://docs.openactive.io/, which replaces all of https://developer.openactive.io/ except for the model aspect, https://developer.openactive.io/ could be refactored to just provide results for the namespace ala schema.org.

So in this case perhaps we have https://openactive.io/Brand instead of https://developer.openactive.io/models/brand, and redirect https://openactive.io/ to https://www.openactive.io/?

We could keep https://openactive.io/docs/full.html as the contents page (mirroring https://schema.org/docs/full.html)?

**Comment by nickevansuk** [comment]
@ldodds also flagging this one for 2.0, as it's a breaking change so good to get in there

**Comment by nickevansuk** [comment]
We've set up a redirect so that `https://openactive.io/*` will forward to `https://www.openactive.io/ns/#*`

Except the base URL which forwards to https://www.openactive.io, and `https://openactive.io/activity-list/*` -> which forwards to  `https://www.openactive.io/activity-list/*`

So should be able to make use of canonical e.g. `https://openactive.io/None` in line with schema.org and get the best of both worlds, with flexibility to move documentation around / create more comprehensive documentation later as needed by simply changing the redirect :)

**Comment by petewalker** [comment]
The namespace of `oa` still has a `www` here: https://www.openactive.io/modelling-opportunity-data/EditorsDraft/#namespaces

Also see https://github.com/openactive/data-model-validator/issues/197#issuecomment-417643883

**Comment by nickevansuk** [comment]
The namespace is planned to change to simply `https://openactive.io/` to match schema.org. There's already content negotiation for the schema in place at that location.

**Comment by petewalker** [comment]
Yes - so, presumably `oa` becomes `https://openactive.io/` ?
It's `https://www.openactive.io/ns/` in the Editor's Draft.

**Comment by nickevansuk** [comment]
Sorry yes I see what you mean, @ldodds still has yet to update all the URLs in the spec (he ran out of time last night just getting core content done)

**Comment by nickevansuk** [comment]
(He's also updating `"@context": "https://openactive.io/ns/oa.jsonld",` to `"@context": "https://openactive.io/"`) for those examples
