### ISSUE TITLE
Flexible identifier

### ISSUE THREAD

**Issue by nickevansuk** [openactive/modelling-opportunity-data#137]
Given that identifier is used purely to represent internal and related IDs, and is not expected to make sense out of context of a particular feed, does it make more sense to allow:

- String and Number (as current)
- PropertyValue
- Array of PropertyValue

This allows it to be used for multiple internal IDs and related IDs, and should have minimal effect on data consumers (who are not looking for uniformity in this property, which is already optional)

**Comment by ldodds** [comment]
We could relax this definition, yes. A string or number seems fine.

Schema.org allows PropertyValue so I can see an argument for keeping it aligned and allowing an array  if there are multiple custom identifiers.

Will include some wording around this in a revised draft.

**Comment by nickevansuk** [comment]
Excellent! Two specific examples of this from real-life usecases: references to Google Places ID, and Active Places ID. See below:

```
{
  "@context": "https://openactive.io/",
  "type": "Event",
  "name": "Tai chi Class",
  "url": "http://www.example.org/events/1",
  "startDate": "2017-03-22T20:00:00Z",
  "activity": [
    {
      "type": "Concept",
      "id": "https://openactive.io/activity-list#72ddb2dc-7d75-424e-880a-d90eabe91381",
      "inScheme": "https://openactive.io/activity-list",
      "prefLabel": "Running"
    }
  ],
  "organizer": {
    "type": "Organization",
    "name": "ExampleCo Gym"
  },
  "location": {
    "type": "Place",
    "name": "ExampleCo Gym Kingswood",
    "identifier": [
      {
        "type": "PropertyValue",
        "propertyID": "https://www.activeplacespower.com/",
        "name": "Active Places ID",
        "value": 6008519
      },
      {
        "type": "PropertyValue",
        "propertyID": "https://developers.google.com/places/place-id",
        "name": "Google Places ID",
        "value": "ChIJdThi040cbkgRXkb46Bd0syD"
      }
    ],
    "address": {
      "type": "PostalAddress",
      "streetAddress": "1 High Street",
      "addressLocality": "Kingswood",
      "addressRegion": "South Gloucestershire",
      "postalCode": "BS1 4SD",
      "addressCountry": "GB"
    }
  }
}
```

**Comment by ldodds** [comment]
Note: the propertyID is intended to be a commonly used identifier, see https://schema.org/propertyID. I'm not clear that the URIs in your examples above fit the bill there.

The URIs would need to be standardised, in order to be reliable for consumers. We don't have to get into that for 2.0, but something to think about.

However, if we start to standardise URIs for different types of identifiers, then we may as well define properties for them, e.g. `oa:activePlacesId`. This is similar to the recommendation on schema.org to use specific properties where possible.

So in my view the use of `PropertyValue` is largely as an escape hatch to allow for multiple identifiers to be used where we/others have not defined how else to support them.

**Comment by nickevansuk** [comment]
+1 to escape hatch. Given that they're designed for the undefined, i guess they'd need to be uncontrolled pre-standardisation.

Not sure what counts as "commonly used" (is it commonly used if a few OA publishers use it?)
