### ISSUE TITLE
Agree on how to represent equipment

### ISSUE THREAD

**Issue by ldodds** [openactive/modelling-opportunity-data#19]
Should equipment be 

* a simple textual description -- fairly limited
* a controlled vocabulary -- allows for some structure
* modelling in some way, e.g. as as `oa:Equipment` class -- may be more detailed than required for simple discovery use cases

**Comment by greywillfade** [comment]
I'd be interested to hear more both from the perspective of activity providers and data users/end consumers. Is this something that people split out at the moment in their back-ends? Is it something that people typically want to search by in detail (e.g. searching by _type_ of equipment)? Is it something that gets searched on at all, or is it more contextual information to be displayed rather than interacted with?

My experience to date with end-user interfaces (consumers searching, browsing) is that there is sometimes a flag as to whether equipment should be brought, and a textual description to accompany it where necessary, but that searching/categorisation/interaction doesn't go deeper than this. Examples could be:

- Equipment needed - please bring towels and goggles
- Equipment involved (gloves and pads) but will be provided
- No equipment is involved (this may not even be shown to end users)

I am yet to see an example of 'show me everything that involves [TOWELS]', etc!

Any real world examples that we can learn from here?

**Comment by ldodds** [comment]
Closing as while this was mentioned early on, its not been raised as a current requirement. We can revisit in future. As @greywillfade notes, the documentation properties cover what to bring already.
