### ISSUE TITLE
How to reference activity types and other concepts

### ISSUE THREAD

**Issue by MikeThacker1** [openactive/modelling-opportunity-data#21]
I’d like to clarify how an activity* from one of possibly many activity lists is expected to be referenced. (And hope this isn't a stupid question.)

The data model shows that an event has an “activity” and I understand that activities are expected to come from SKOS lists.  

**Will every activity therefore have a URI from which its conceptScheme (and other properties like broader and narrower activities) can be derived?**

If activities are referenced by multiple lists (of activity types, surfaces, etc) in the absence (at least initially) of one common list, will every list owner be expected to express its list as a SKOS concept scheme with a standardised approach for de-referencing?

FYI, in looser local government work (oten using CSV as a data exchange format) we’ve asked data publishers to describe concepts with as many of these properties as they can:
•	Label – a text title / name
•	Scheme – a text reference (a kind of namespace) from which a scheme can be identified
•	Base URI – the stub of the concept URI, which might be the URI of the whole concept scheme
•	Code – the final part of the URI
•	Full URI – a concatenation of the above two, which should be sufficient if it exists and is dereferencable

'* BTW I understand “activity” to mean “activity type” (and have learned from experience of people discussing the SKOS lists that [esd-standards](http://standards.esd.org.uk/) maintains that each of our SKOS lists describes _types_ of thing) .

**Comment by ldodds** [comment]
Here's how it will look based on the current specification:

https://www.openactive.io/modelling-opportunity-data/#relating-events-to-physical-activities

Because of the variety of ways in which the data is currently managed, we won't be requiring URIs for everything, but are encouraging use of SKOS and provision of identifiers and notations where available.

I've not looked at CSV format for these lists but plan on doing that this week. It's likely to follow a simple model though. For now we have to be flexible.

Once we've converged on a recommended list then we can be more prescriptive.
