### ISSUE TITLE
Decide how to model venue facilities

### ISSUE THREAD

**Issue by ldodds** [openactive/modelling-opportunity-data#5]
We will probably need to describe facilities at venues. E.g. that there are table tennis tables that a sports club. Schema.org has an `amenityFeature` which can be used to list facilities.

* Is this sufficient?
* Do we need a controlled vocabulary?

**Comment by nickpde** [comment]
Leigh

You may want to look at the Active Places data model which shows how we relate sites (venues) with facilities.  In effect one site or venue can have many facilities. This a relatively mature model and has been in place since 2004.
In terms of the example you have provided, we would see this as site equipment and not a facility. The issue with table tennis tables is that they can be moved around facilities within a venue and set up in a sports hall, squash court etc.  This is a working version of the one on the Active Places Power website [https://www.activeplacespower.com/sdm](url) and is more up to date as it contains cycling definitions which have recently been agreed with British Cycling.
[Active Places SDM inc Data Management Platform V1.xlsx](https://github.com/openactive/modelling-opportunity-data/files/714102/Active.Places.SDM.inc.Data.Management.Platform.V1.xlsx)

**Comment by ldodds** [comment]
That's great, thanks @nickpde will explore that.
