### ISSUE TITLE
Price should always be a string with 2 decimal places

### ISSUE THREAD

**Issue by nickevansuk** [openactive/modelling-opportunity-data#92]
## Proposer

ODI

## Use Case

It is important to represent price consistently, without currency, and allow it to be easily displayed and parsed.

## Proposal

We have been recommending this to be a string with 2 decimal places in accordance with the most prominent recommendation here: https://schema.org/price. For the avoidance of doubt, this should be included in the specification.

## Associated validation rules

- https://github.com/openactive/developer-microsite/issues/15

**Comment by jamiefoale** [comment]
For API consumers using functional programming (I'm thinking Scala), having a decimal number presented as a string in the JSON is a bit annoying.

**Comment by nickevansuk** [comment]
Great point regarding Scala. One issue with the decimal type: if the price is provided as a decimal type that exceeds 2 decimal places, the price must be rounded in a consistent manner in order to ensure that the correct price is displayed and charged for the booking.

A validation rule for the decimal type would also solve this, so then the question becomes: is validating the price to 2dp easier as a string or as a decimal?

**Comment by petewalker** [comment]
It's pretty easy to validate a float's precision in JavaScript:

```js
let number = 10.456;
Math.ceil(number * 100) === Math.floor(number * 100)
// false
number = 10.45;
Math.ceil(number * 100) === Math.floor(number * 100)
// true
number = 10;
Math.ceil(number * 100) === Math.floor(number * 100)
// true
```

**Comment by petewalker** [comment]
As discussed with @ldodds this afternoon...

I've been having fun validating decimal types for `GeoCoordinates` and `price` in the validator project. It's basically impossible to test precision exactly in any programming language, because of what they all do with trailing zeros:

Most languages drop trailing zeros - for example:

JavaScript
```js
// JS
1.20
// => 1.2
String(1.20)
// => "1.2"
```

PHP
```php
var_dump(1.20);
// => float(1.2)
var_dump('' . 1.20);
// => string(3) "1.2"
```

Ruby
```ruby
n = 1.20
# => 1.2
n.to_s
# => "1.2"
(1.20).to_s
# => "1.2"
```

Validating this correctly when the type of the incoming data is a float will yield some false negatives.

For this reason, I'm an advocate for strings for floating point numbers. Paypal is a good example of a prominent vendor using strings for price in an API: https://developer.paypal.com/docs/api/payments/v1/#payment-create-header-parameters

**Comment by nickevansuk** [comment]
Stripe uses strings for prices too, however maybe I'm missing something here? The previous suggestion (https://github.com/openactive/modelling-opportunity-data/issues/92#issuecomment-405892079) of using `ceil` and `floor` works to ensure no excess precision for pricing? Isn't that all we need to protect against?

For geo I see the issue as we're testing for sufficient precision rather than excess precision, but even  then a string wouldn't help as most libraries wouldn't render extra 0s when rendered float to string?

So for both cases not sure what string solves here?

**Comment by petewalker** [comment]
For price that's true - although if we have a low sample size from a validator perspective, we may be giving false positives.

For GeoCoordinates, again if we have a small sample size for the validator, we may give out false negatives. It's this grey area that makes me uneasy... it's not very precise!

**Comment by petewalker** [comment]
To add to the above, it's like the difference between:

> Your feed _definitely_ complies

vs.

> Your feed _probably_ complies

Take for example a vendor that today has classes that are always £5. Today our validator says their feed is fine, because the precision is correct.

```json
{
    price: 5
}
```

Next week they decide to run a promotion, and apply a third off everything. They apply a discount to their system in whatever software they use, and the price is now:

```json
{
    price: 3.3333333333333333
}
```

This is what (apparently) keeps me awake at night...!

**Comment by nickevansuk** [comment]
Totally see what you mean! Mind you the same sample size problem exists if the objective is to prevent the below (string version of the same).

```
{
    "price": “3.3333333333333333”
}
```

I’d suggest this is more a “data quality rule” for geo reason, which just provides advice, as you say otherwise there might be false negatives. The same applies to the HTML rule that detects HTML in plain text strings: it depends very much on the sample!

False positives for price seem unavoidable, but then at its extreme unless we are running this over the whole feed (which aggregators using this library plan to do) we can’t be certain that there isn’t some strange conditional that inserts ASCII chickens into the startDate field one in every 10,000 cases 🐔 

Validating an RPDE list becomes more important for this reason

**Comment by ldodds** [comment]
After much back and forth, I think we are going to go with numeric value. We will generate warning if the price is specified to more than two decimal places.
